name: CI

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: wyvox/action-setup-pnpm@v3
        with: { node-version: 22, pnpm-version: 9 }

      - name: start qbittorrent
        run: |
          mkdir -p ~/.config/qBittorrent/
          cat > ~/.config/qBittorrent/qBittorrent.conf << 'EOF'
          [BitTorrent]
          Session\QueueingSystemEnabled=false
          [Meta]
          MigrationVersion=6
          [Preferences]
          WebUI\Password_PBKDF2="@ByteArray(ARQ77eY1NUZaQsuDHbIMCA==:0WMRkYTUWVT9wVvdDtHAjU9b3b7uB8NR1Gur2hmQCvCDpm39Q+PsJRJPaCU51dEiz+dTzh8qbPsL8WkFljQYFQ==)"
          EOF
          sudo add-apt-repository ppa:qbittorrent-team/qbittorrent-stable
          sudo apt update
          sudo apt install qbittorrent-nox
          qbittorrent-nox -d
          sudo mkdir /downloads
          mkdir ~/downloads

      - name: lint
        run: pnpm run lint

      - run: cat ~/.config/qBittorrent/qBittorrent.conf

      - name: test
        run: pnpm run test:ci

      - name: coverage
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}

  publish:
    needs: build
    runs-on: ubuntu-latest
    if: github.ref_name == 'master'
    permissions:
      contents: write # to be able to publish a GitHub release
      issues: write # to be able to comment on released issues
      pull-requests: write # to be able to comment on released pull requests
      id-token: write # to enable use of OIDC for npm provenance
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: wyvox/action-setup-pnpm@v3
        with: { node-version: 22, pnpm-version: 9 }

      - name: release
        run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
