name: CI

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # https://github.com/actions/checkout
      - uses: actions/checkout@v6

      # https://github.com/wyvox/action-setup-pnpm
      - uses: wyvox/action-setup-pnpm@v3
        with:
          node-version: 24

      - name: start qbittorrent
        # creates a default config with password adminadmin
        run: |
          mkdir -p ~/.config/qBittorrent/
          cat > ~/.config/qBittorrent/qBittorrent.conf << 'EOF'
          [BitTorrent]
          Session\QueueingSystemEnabled=false
          [Meta]
          MigrationVersion=6
          [Preferences]
          WebUI\Password_PBKDF2="@ByteArray(ARQ77eY1NUZaQsuDHbIMCA==:0WMRkYTUWVT9wVvdDtHAjU9b3b7uB8NR1Gur2hmQCvCDpm39Q+PsJRJPaCU51dEiz+dTzh8qbPsL8WkFljQYFQ==)"
          EOF
          sudo add-apt-repository ppa:qbittorrent-team/qbittorrent-stable
          sudo apt update
          sudo apt install qbittorrent-nox
          qbittorrent-nox -d
          sudo mkdir /downloads
          mkdir ~/downloads

      - name: lint
        run: pnpm run lint

      - name: test
        run: pnpm run test
